version: "3.7"

services:
  app_1:
    container_name: app1
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - PROMETHEUS_MULTIPROC_DIR=/app/metrics
    ports:
      - "8001:8001"
    #command: python manage.py runserver 0.0.0.0:8000
    #command: uwsgi --module my_app.wsgi --socket 0.0.0.0:8001 --master --processes=2 -b 131072
    command: uwsgi --ini uwsgi.ini
  
  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    volumes:
      - ./prometheus/:/etc/prometheus/
    ports:
      - "9090:9090"

  grafana:
    container_name: grafana
    image: grafana/grafana:latest
    volumes:
      - ./grafana/:/var/lib/grafana/
    ports:
      - "3000:3000"
    #restart: unless-stopped

  nginx:
    container_name: nginx
    image: nginx:latest
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/uwsgi_params:/etc/nginx/uwsgi_params
    ports:
      - "8000:8000"
    depends_on:
      - "app_1"