global:
  scrape_interval: 10s
  evaluation_interval: 10s

rule_files:
  - http.rules

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
        - nginx:8000