global:
  scrape_interval: 5s
  evaluation_interval: 5s

rule_files:
  - http.rules

scrape_configs:
  - job_name: monitoring
    metrics_path: /metrics
    static_configs:
      - targets:
        - app1:8000
        - app2:8080